codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "!**/*_test.go"
          - "!**/testdata/**"
          - "!**/mocks/**"
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/testdata"
  - "**/mocks"
  - "**/*.pb.go"
  - "**/vendor/**"
  - "docs/**"
  - "*.md"

flags:
  unittests:
    paths:
      - "!**/*_test.go"
    carryforward: true